
name: CI

on:
  push:
    branches: [master]
  pull-request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Runa one-line script
    run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        eche test, and deploy your project.